all: info build run

build:
	zig build

run:
	zig build run -- ../../../inputs/2015/7.txt

info:
	@echo "If not running fetch new hash for zig-string library and replace build.zig.zon entry with the new hash. Use zig fetch url"
