input_file = ../../../inputs/2015/6.txt

build: build-part1 build-part2

run:
	dotnet run --project part1 $(input_file) && dotnet run --project part2 $(input_file)

build-part1:
	dotnet build part1

build-part2:
	dotnet build part2